# Generated by Django 5.2.5

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('survey_type', models.CharField(choices=[('anonymous', 'Анонимный'), ('authenticated', 'С авторизацией')], default='authenticated', max_length=20, verbose_name='Тип опроса')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активный'), ('paused', 'Приостановлен'), ('closed', 'Закрыт')], default='draft', max_length=20, verbose_name='Статус')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный')),
                ('requires_login', models.BooleanField(default=True, verbose_name='Требует авторизации')),
                ('allow_multiple_responses', models.BooleanField(default=False, verbose_name='Разрешить множественные ответы')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('text', 'Текстовый ответ'), ('textarea', 'Многострочный текст'), ('single_choice', 'Один выбор'), ('multiple_choice', 'Множественный выбор'), ('rating', 'Рейтинг'), ('scale', 'Шкала'), ('date', 'Дата'), ('time', 'Время'), ('datetime', 'Дата и время')], max_length=20, verbose_name='Тип вопроса')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('help_text', models.TextField(blank=True, verbose_name='Подсказка')),
                ('min_choices', models.PositiveIntegerField(default=1, verbose_name='Минимум выборов')),
                ('max_choices', models.PositiveIntegerField(default=1, verbose_name='Максимум выборов')),
                ('min_value', models.IntegerField(default=1, verbose_name='Минимальное значение')),
                ('max_value', models.IntegerField(default=5, verbose_name='Максимальное значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст варианта')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id', models.CharField(blank=True, max_length=100, verbose_name='Анонимный ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало заполнения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение заполнения')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey', verbose_name='Опрос')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ на опрос',
                'verbose_name_plural': 'Ответы на опросы',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='Текстовый ответ')),
                ('numeric_answer', models.IntegerField(blank=True, null=True, verbose_name='Числовой ответ')),
                ('date_answer', models.DateField(blank=True, null=True, verbose_name='Ответ - дата')),
                ('time_answer', models.TimeField(blank=True, null=True, verbose_name='Ответ - время')),
                ('datetime_answer', models.DateTimeField(blank=True, null=True, verbose_name='Ответ - дата и время')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question', verbose_name='Вопрос')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyresponse', verbose_name='Ответ на опрос')),
                ('selected_choices', models.ManyToManyField(blank=True, to='surveys.questionchoice', verbose_name='Выбранные варианты')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'unique_together': {('response', 'question')},
            },
        ),
    ]